#!/usr/bin/env python3
"""Build ``generated/cities_data.lua``: the 10 most-populous cities per country.

Data source: the ``geonamescache`` package (bundled GeoNames extract, offline).
Each city carries a display name, its country, an ISO-3166 alpha-2 code (lower
case, matching worldmap_data) and WGS84 ``lat``/``lon``.  The runtime Fuse loads
this to populate a searchable City combo and to place a marker dot.

Usage::

    python tools/build_cities_data.py [--out PATH] [--top N] [--precision P]
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

import geonamescache

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "generated" / "cities_data.lua"


def _fmt(value: float, precision: int) -> str:
    s = f"{value:.{precision}f}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    if s in ("-0", ""):
        s = "0"
    return s


def _lua_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build(out_path: Path, top: int, precision: int) -> dict:
    gc = geonamescache.GeonamesCache()
    country_names = {code: c["name"] for code, c in gc.get_countries().items()}

    # Group cities by country code.
    by_country: dict[str, list[dict]] = {}
    for city in gc.get_cities().values():
        cc = city.get("countrycode")
        if not cc:
            continue
        by_country.setdefault(cc, []).append(city)

    rows: List[dict] = []
    for cc, cities in by_country.items():
        # De-duplicate by name (keep the most populous), then take the top N.
        best: dict[str, dict] = {}
        for c in cities:
            name = c["name"]
            if name not in best or c["population"] > best[name]["population"]:
                best[name] = c
        chosen = sorted(best.values(), key=lambda c: c["population"], reverse=True)[:top]
        cname = country_names.get(cc, cc)
        for c in chosen:
            rows.append({
                "name": c["name"],
                "country": cname,
                "code": cc.lower(),
                "lat": c["latitude"],
                "lon": c["longitude"],
            })

    # Sort alphabetically by city name so the combo's type-ahead search works.
    rows.sort(key=lambda r: (r["name"].lower(), r["country"].lower()))

    lines: List[str] = []
    lines.append("-- =====================================================")
    lines.append("-- AUTO-GENERATED by tools/build_cities_data.py")
    lines.append("-- DO NOT EDIT MANUALLY. Regenerate from geonamescache.")
    lines.append(f"-- top {top} cities per country by population")
    lines.append("-- =====================================================")
    lines.append("local M = {}")
    lines.append("M.cities = {")
    for r in rows:
        lines.append(
            "{name=" + _lua_string(r["name"])
            + ",country=" + _lua_string(r["country"])
            + ",code=" + _lua_string(r["code"])
            + ",lat=" + _fmt(r["lat"], precision)
            + ",lon=" + _fmt(r["lon"], precision) + "},"
        )
    lines.append("}")
    lines.append("return M")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    return {
        "cities": len(rows),
        "countries": len(by_country),
        "bytes": out_path.stat().st_size,
    }


def main(argv: List[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--top", type=int, default=10)
    ap.add_argument("--precision", type=int, default=4)
    args = ap.parse_args(argv)

    summary = build(args.out, args.top, args.precision)
    print("Cities data built:")
    for k, v in summary.items():
        print(f"  {k}: {v}")
    print(f"  -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
