#!/usr/bin/env python3
"""Build ``generated/worldmap_data.lua`` from ``assets/BlankMap-World.svg``.

Stage 1 of the two-stage architecture: parse and normalise the 1 MB SVG exactly
once into a compact, deterministic Lua table that the runtime Fuse loads.  The
runtime never parses SVG.

Usage::

    python tools/build_worldmap_data.py [--quality draft|normal|high]
                                        [--svg PATH] [--out PATH]

The output is deterministic for a given input + options.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import List, Tuple

# Allow running both as a module and as a script.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from worldmap import projection
from worldmap.countries import Country, build_countries
from worldmap.geometry import Contour, FlattenOptions

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SVG = REPO_ROOT / "assets" / "BlankMap-World.svg"
DEFAULT_OUT = REPO_ROOT / "generated" / "worldmap_data.lua"

QUALITY_TOLERANCE = {"draft": 1.2, "normal": 0.5, "high": 0.25}

GeoContour = List[Tuple[float, float]]


def pixels_to_geo(polys_px: List[Contour]) -> List[GeoContour]:
    """Convert pixel contours to geographic ``(lon, lat)`` contours."""
    out: List[GeoContour] = []
    for contour in polys_px:
        geo = [projection.inverse(px, py) for px, py in contour]
        out.append(geo)
    return out


def _fmt(value: float, precision: int) -> str:
    """Format a float compactly and deterministically."""
    s = f"{value:.{precision}f}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    if s in ("-0", ""):
        s = "0"
    return s


def _lua_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _emit_polys(polys: List[GeoContour], precision: int, out: List[str]) -> None:
    out.append("polys={")
    for contour in polys:
        nums = []
        for lon, lat in contour:
            nums.append(_fmt(lon, precision))
            nums.append(_fmt(lat, precision))
        out.append("{" + ",".join(nums) + "},")
    out.append("}")


def build(svg_path: Path, out_path: Path, quality: str, precision: int) -> dict:
    """Run the full build and write the Lua data file. Returns a summary dict."""
    tol = QUALITY_TOLERANCE[quality]
    opts = FlattenOptions(tolerance_px=tol)

    svg_bytes = svg_path.read_bytes()
    src_hash = hashlib.sha256(svg_bytes).hexdigest()[:16]

    root = __import__("worldmap.svg_parser", fromlist=["load"]).load(str(svg_path))
    countries, world, disputed = build_countries(root, opts)

    # Convert every country's geometry to geographic coordinates.
    geo_countries: List[Tuple[Country, List[GeoContour]]] = []
    total_vertices = 0
    for c in countries:
        geo = pixels_to_geo(c.polys_px)
        total_vertices += sum(len(g) for g in geo)
        geo_countries.append((c, geo))
    world_geo = pixels_to_geo(world.polys_px) if world else []
    total_vertices += sum(len(g) for g in world_geo)
    disputed_geo = pixels_to_geo(disputed)
    total_vertices += sum(len(g) for g in disputed_geo)

    lines: List[str] = []
    lines.append("-- =====================================================")
    lines.append("-- AUTO-GENERATED by tools/build_worldmap_data.py")
    lines.append("-- DO NOT EDIT MANUALLY. Regenerate from the source SVG.")
    lines.append("-- source: assets/BlankMap-World.svg  sha256[:16]=" + src_hash)
    lines.append("-- quality=" + quality + " precision=" + str(precision))
    lines.append("-- =====================================================")
    lines.append("local M = {}")
    lines.append("M.meta = {")
    lines.append('  source="BlankMap-World.svg", projection="robinson",')
    lines.append(f"  src_hash={_lua_string(src_hash)}, quality={_lua_string(quality)},")
    lines.append(f"  width={_fmt(projection.SVG_WIDTH, 0)}, "
                 f"height={_fmt(projection.SVG_HEIGHT, 0)},")
    lines.append(f"  CX={projection.CX}, KX={projection.KX}, "
                 f"CY={projection.CY}, KY={projection.KY},")
    lines.append("}")

    # Robinson table for the runtime forward projection.
    lines.append("M.robinson = {")
    lines.append("  lats={" + ",".join(_fmt(v, 0) for v in projection.LATS) + "},")
    lines.append("  xs={" + ",".join(_fmt(v, 4) for v in projection.XS) + "},")
    lines.append("  ys={" + ",".join(_fmt(v, 4) for v in projection.YS) + "},")
    lines.append("}")

    # World boundary.
    lines.append("M.world = {")
    _emit_polys(world_geo, precision, lines)
    lines.append("}")

    # Disputed / limited-recognition borders (optional overlay).
    lines.append("M.disputed = {")
    _emit_polys(disputed_geo, precision, lines)
    lines.append("}")

    # Countries (ordered, selectable).
    lines.append("M.countries = {")
    for c, geo in geo_countries:
        lines.append("{code=" + _lua_string(c.code) + ",name=" + _lua_string(c.name)
                     + ",kind=" + _lua_string(c.kind) + ",")
        _emit_polys(geo, precision, lines)
        lines.append("},")
    lines.append("}")
    lines.append("return M")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    return {
        "countries": len(countries),
        "vertices": total_vertices,
        "world_rings": len(world_geo),
        "disputed_rings": len(disputed_geo),
        "bytes": out_path.stat().st_size,
        "src_hash": src_hash,
        "quality": quality,
    }


def main(argv: List[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--svg", type=Path, default=DEFAULT_SVG)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--quality", choices=list(QUALITY_TOLERANCE), default="normal")
    ap.add_argument("--precision", type=int, default=4)
    args = ap.parse_args(argv)

    if not args.svg.exists():
        ap.error(f"source SVG not found: {args.svg}")

    summary = build(args.svg, args.out, args.quality, args.precision)
    print("WorldMap data built:")
    for k, v in summary.items():
        print(f"  {k}: {v}")
    print(f"  -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
